# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'install Node.js'

- script: |
    npm install -g @angular/cli@7.2.2
    npm install -g tslint typescript@3.2.4
    npm install
  displayName: 'npm install'

- script: tslint --project ./
  displayName: 'static analysis using tslint'

- script: npm run build:ssr
  displayName: 'build:ssr'
  
- task: CopyFiles@2
  inputs:
    Contents: |
      **/dist/**
      !**/node_modules/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'copy all to staging'

- task: CopyFiles@2
  inputs:
    Contents: web.config
    TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'
  displayName: 'copy web.config to staging'

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'